### ISSUE TITLE
Fix Github Actions workflow deployment

### ISSUE THREAD

**Issue by dploeger** [godotengine/escoria#328]
As an Escoria developer I'd like to fix the Github Actions workflow deployment introduced in #327 as it is broken due to the protected branches rules.

To achieve this, one account (I'd suggest @StraToN ) needs to be allowed to push to main in the branch protection rule for main. 

That account needs to create a [GitHub access token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) and create a new [GitHub Action secret](https://docs.github.com/en/actions/reference/encrypted-secrets) named `DEPLOYMENT_TOKEN` with this access token.

Once this is done, the secret needs to be referenced in the workflow like this:

```
            - name: Checkout
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.DEPLOYMENT_TOKEN }}
```
